version: "3.5"
services:
  webserver:
    image: nginx:alpine
    container_name: loghub-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"

  php-fpm:
    build: ./docker-config/php-fpm
    container_name: loghub-php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-config/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

#version: '2'
#services:
#  php:
#    image: yiisoftware/yii2-php:7.4-apache
#    volumes:
#      - ~/.composer-docker/cache:/root/.composer/cache:delegated
#      - ./:/app:delegated
#    ports:
#      - '8000:80'
#