version: "3.5"
services:
  webserver:
    image: nginx:alpine
    container_name: loghub-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"

  php-fpm:
    build: ./docker-config/php-fpm
    container_name: loghub-php-fpm
    environment:
      - PHP_IDE_CONFIG=serverName=docker
    working_dir: /application
    volumes:
      - .:/application
      - ./docker-config/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

  clickhouse:
    image: yandex/clickhouse-server
    container_name: loghub-clickhouse
    volumes:
      - ./docker-config/clickhouse/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - ./docker-config/clickhouse/data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
